name: build

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: deploy to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ runner.python-version }}-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-pip-${{ runner.python-version }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dunamai setuptools wheel twine
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/* --verbose
  install:
    name: test wheel installation
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Retrieve version from repository
        uses: mtkennerly/dunamai-action@v1
        with:
          env-var: VERSION
      - name: Install wheel
        run: |
          python -m pip install --upgrade pip
          pip install nemspy==$VERSION
